const nodemailer = require('nodemailer');
const { getFirestore } = require('../config/firebase');

// Configure email transporter
const transporter = nodemailer.createTransport({
  service: 'gmail', // or your preferred email service
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS
  }
});

const sendEmergencyNotifications = async (userId, emergencyData) => {
  try {
    const db = getFirestore();
    
    // Get user's trusted contacts
    const userDoc = await db.collection('users').doc(userId).get();
    if (!userDoc.exists) {
      throw new Error('User not found');
    }
    
    const userData = userDoc.data();
    const trustedContacts = userData.trustedContacts || [];
    
    if (trustedContacts.length === 0) {
      console.log('No trusted contacts found for user:', userId);
      return;
    }
    
    // Prepare emergency details
    const emergencyDetails = formatEmergencyDetails(emergencyData);
    
    // Send notifications to all trusted contacts
    const notificationPromises = trustedContacts.map(contact => 
      sendEmergencyEmail(contact, userData, emergencyDetails)
    );
    
    await Promise.all(notificationPromises);
    console.log(`Emergency notifications sent to ${trustedContacts.length} contacts`);
    
  } catch (error) {
    console.error('Failed to send emergency notifications:', error);
    throw error;
  }
};

const sendEmergencyEmail = async (contact, userData, emergencyDetails) => {
  const subject = `🚨 EMERGENCY ALERT - ${userData.name || 'SilentSOS User'}`;
  
  const htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background-color: #dc2626; color: white; padding: 20px; text-align: center;">
        <h1>🚨 EMERGENCY ALERT</h1>
        <p style="font-size: 18px; margin: 0;">SilentSOS has detected a potential emergency</p>
      </div>
      
      <div style="padding: 20px; background-color: #f9f9f9;">
        <h2>Emergency Details</h2>
        <p><strong>Person:</strong> ${userData.name || 'SilentSOS User'}</p>
        <p><strong>Time:</strong> ${new Date(emergencyDetails.timestamp).toLocaleString()}</p>
        <p><strong>Confidence Level:</strong> ${emergencyDetails.confidence}%</p>
        
        ${emergencyDetails.location ? `
          <h3>Location</h3>
          <p><strong>Coordinates:</strong> ${emergencyDetails.location.latitude}, ${emergencyDetails.location.longitude}</p>
          <p><a href="https://maps.google.com/?q=${emergencyDetails.location.latitude},${emergencyDetails.location.longitude}" 
                style="color: #dc2626; text-decoration: none;">📍 View on Google Maps</a></p>
        ` : ''}
        
        <h3>Detection Factors</h3>
        <ul>
          ${emergencyDetails.factors.map(factor => `<li>${factor}</li>`).join('')}
        </ul>
        
        <div style="background-color: #fef3c7; padding: 15px; border-radius: 5px; margin: 20px 0;">
          <h3 style="color: #92400e; margin-top: 0;">What to do:</h3>
          <ol style="color: #92400e;">
            <li>Try to contact ${userData.name || 'the person'} immediately</li>
            <li>If no response, consider calling emergency services</li>
            <li>Check the live dashboard for updates</li>
          </ol>
        </div>
        
        <div style="text-align: center; margin: 30px 0;">
          <a href="${process.env.CLIENT_URL}/dashboard" 
             style="background-color: #dc2626; color: white; padding: 15px 30px; text-decoration: none; border-radius: 5px; display: inline-block;">
            View Live Dashboard
          </a>
        </div>
        
        <div style="border-top: 1px solid #ddd; padding-top: 20px; margin-top: 30px; font-size: 12px; color: #666;">
          <p>This alert was automatically generated by SilentSOS emergency detection system.</p>
          <p>Emergency ID: ${emergencyDetails.id}</p>
          <p>If this is a false alarm, the person can cancel it from their device.</p>
        </div>
      </div>
    </div>
  `;
  
  const mailOptions = {
    from: process.env.EMAIL_USER,
    to: contact.email,
    subject: subject,
    html: htmlContent
  };
  
  try {
    await transporter.sendMail(mailOptions);
    console.log(`Emergency email sent to: ${contact.email}`);
  } catch (error) {
    console.error(`Failed to send email to ${contact.email}:`, error);
  }
};

const formatEmergencyDetails = (emergencyData) => {
  const factors = [];
  
  // Extract human-readable factors from breakdown
  if (emergencyData.breakdown) {
    if (emergencyData.breakdown.sensorScore > 20) {
      factors.push(`Sensor anomalies detected (${emergencyData.breakdown.sensorScore}% confidence)`);
    }
    if (emergencyData.breakdown.contextScore > 10) {
      factors.push(`High-risk context factors (${emergencyData.breakdown.contextScore}% risk)`);
    }
    if (emergencyData.breakdown.locationScore > 10) {
      factors.push(`Location-based risk factors (${emergencyData.breakdown.locationScore}% risk)`);
    }
    if (emergencyData.breakdown.crowdScore > 0) {
      factors.push(`Correlated signals from nearby users`);
    }
  }
  
  // Add specific sensor details if available
  if (emergencyData.sensorData) {
    if (emergencyData.sensorData.motion?.suddenImpact) {
      factors.push(`Sudden impact detected (${emergencyData.sensorData.motion.suddenImpact.magnitude.toFixed(1)}g)`);
    }
    if (emergencyData.sensorData.audio?.silenceDuration > 600) {
      factors.push(`Prolonged silence detected (${Math.round(emergencyData.sensorData.audio.silenceDuration/60)} minutes)`);
    }
    if (emergencyData.sensorData.motion?.stillnessDuration > 300) {
      factors.push(`Extended inactivity detected`);
    }
  }
  
  if (factors.length === 0) {
    factors.push('Multiple emergency indicators detected');
  }
  
  return {
    id: emergencyData.id,
    timestamp: emergencyData.timestamp,
    confidence: Math.round(emergencyData.confidence),
    location: emergencyData.location,
    factors: factors
  };
};

module.exports = {
  sendEmergencyNotifications,
  sendEmergencyEmail,
  formatEmergencyDetails
};